services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Chicago
    volumes:
      - config:/config
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_415005E2-if01-port0:/dev/ttyZigbee

  matter-server:
    container_name: matter-server
    image: ghcr.io/matter-js/python-matter-server:stable
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - matter-data:/data
      - /run/dbus:/run/dbus:ro

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:stable
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Chicago
    volumes:
      - esphome-config:/config

  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    network_mode: host
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=America/Chicago
      - SESSION_SECRET=changeme
    volumes:
      - zwavejs-config:/usr/src/app/store
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_415005E2-if00-port0:/dev/zwave

volumes:
  config:
  matter-data:
  esphome-config:
  zwavejs-config:
