services:
  dns-server:
    container_name: Technitium
    hostname: dns01
    image: docker.io/technitium/dns-server:latest
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5380' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    network_mode: host
    environment:
      - DNS_SERVER_DOMAIN=joeloveless.net
      - DNS_SERVER_LOG_FOLDER_PATH=/opt/technitium/logs
      - TZ=America/Chicago
    volumes:
      - config:/etc/dns:rw
      - logs:/opt/technitium/logs
    restart: unless-stopped

volumes:
  config:
  logs:
