services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest
    container_name: NZBGet
    environment:
       PUID: ${PUID}
       PGID: ${PGID}
       TZ: ${TZ}
       NZBGET_USER: ${NZBGET_USER}
       NZBGET_PASS: ${NZBGET_PASS}
    volumes:
      - /opt/media/nzbget/config:/config
      - media_data:/data
    ports:
      - 6789:6789
    extra_hosts:
      - ultron.local:192.168.4.125
    restart: on-failure:5

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: Prowlarr
    environment:
       PUID: ${PUID}
       PGID: ${PGID}
       TZ: ${TZ}
       PROWLARR__AUTH__METHOD: External
       PROWLARR__AUTH__REQUIRED: Enabled
    volumes:
      - /opt/media/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    environment:
       PUID: ${PUID}
       PGID: ${PGID}
       TZ: ${TZ}
       RADARR__AUTH__METHOD: External
       RADARR__AUTH__REQUIRED: Enabled
    volumes:
      - /opt/media/radarr/config:/config
      - media_data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: Sonarr
    environment:
       PUID: ${PUID}
       PGID: ${PGID}
       TZ: ${TZ}
       SONARR__AUTH__METHOD: External
       SONARR__AUTH__REQUIRED: Enabled
    volumes:
      - /opt/media/sonarr/config:/config
      - media_data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: Lidarr
    environment:
       PUID: ${PUID}
       PGID: ${PGID}
       TZ: ${TZ}
       LIDARR__AUTH__METHOD: External
       LIDARR__AUTH__REQUIRED: Enabled
    volumes:
      - /opt/media/lidarr/config:/config
      - media_data:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: Bazarr
    environment:
       PUID: ${PUID}
       PGID: ${PGID}
       TZ: ${TZ}
    volumes:
      - /opt/media/bazarr/config:/config
      - media_data:/data
    ports:
      - 6767:6767
    restart: unless-stopped

volumes:
  media_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NAS_HOST},rw,nfsvers=3"
      device: ":/volume1/data"
