---
- name: Deploy Caddyfile
  hosts: "{{ target_hosts | default('caddy00') }}"
  become: true
  tasks:
    - name: Copy Caddyfile
      copy:
        src: ../../../../opt/pve00/caddy00/docker/Caddyfile
        dest: /opt/pve00/caddy00/docker/Caddyfile
        mode: "0644"

    - name: Restart Caddy
      command: docker restart caddy
